[toolchain]
profile = "minimal"
channel = "nightly-2025-12-12"
components = ["rust-src", "llvm-tools"]
targets = [
    "riscv64gc-unknown-none-elf",
    "aarch64-unknown-none-softfloat",
    "x86_64-unknown-none",
    "loongarch64-unknown-none",
]
